export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK = 'AUTH_CHECK';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const WRITE_POST = 'WRITE_POST';
export const WRITE_POST_START = 'WRITE_POST_START';
export const WRITE_POST_SUCCESS = 'WRITE_POST_SUCCESS';
export const WRITE_POST_FAIL = 'WRITE_POST_FAIL';

export const GET_POST = 'GET_POST';
export const GET_POST_START = 'GET_POST_START';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAIL = 'GET_POST_FAIL';

export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_POST_START = 'UPDATE_POST_START';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL';

export const GET_LIST = 'GET_LIST';
export const GET_LIST_START = 'GET_LIST_START';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_FAIL = 'GET_LIST_FAIL';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const STORE_POST_ID = 'STORE_POST_ID';

export const GET_MY_LIST_START = 'GET_MY_LIST_START';
export const GET_MY_LIST_SUCCESS = 'GET_MY_LIST_SUCCESS';
export const GET_MY_LIST_FAIL = 'GET_MY_LIST_FAIL';

export const GET_USER_INFO_START = 'GET_USER_INFO_START';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL';

export const GET_PEOPLE_START = 'GET_PEOPLE_START';
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const GET_PEOPLE_FAIL = 'GET_PEOPLE_FAIL';
