// AUTH actionTypes
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_SAVE_FOLLOW = 'AUTH_SAVE_FOLLOW';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_CHECK = 'AUTH_CHECK';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FOLLOW = 'FOLLOW';
export const RELOAD_FOLLOW = 'RELOAD_FOLLOW';
// export const FOLLOWING_SUCCESS = 'FOLLOWING_SUCCESS';
// export const FOLLOWER_SUCCESS = 'FOLLOWER_SUCCESS';

// EDITOR actionTypes
export const WRITE_POST = 'WRITE_POST';
export const WRITE_POST_START = 'WRITE_POST_START';
export const WRITE_POST_SUCCESS = 'WRITE_POST_SUCCESS';
export const WRITE_POST_FAIL = 'WRITE_POST_FAIL';

export const EDIT_POST = 'EDIT_POST';
export const EDIT_POST_START = 'EDIT_POST_START';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const EDIT_POST_FAIL = 'EDIT_POST_FAIL';
export const INIT_EDIT = 'INIT_EDIT';

// POST actionTypes
export const GET_POST = 'GET_POST';
export const GET_POST_START = 'GET_POST_START';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAIL = 'GET_POST_FAIL';

export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_POST_START = 'UPDATE_POST_START';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_START = 'DELETE_POST_START';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';
export const INIT_DELETE = 'INIT_DELETE';

export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_START = 'DELETE_COMMENT_START';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';

export const STORE_POST_ID = 'STORE_POST_ID';

// LIST actionTypes
export const GET_LIST = 'GET_LIST';
export const GET_LIST_START = 'GET_LIST_START';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_FAIL = 'GET_LIST_FAIL';

export const GET_MY_LIST = 'GET_MY_LIST';
export const GET_MY_LIST_START = 'GET_MY_LIST_START';
export const GET_MY_LIST_SUCCESS = 'GET_MY_LIST_SUCCESS';
export const GET_MY_LIST_FAIL = 'GET_MY_LIST_FAIL';

// BASE actionTypes
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

// USER actionTypes
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_START = 'GET_USER_INFO_START';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL';

// PEOPLE actionTypes
export const GET_PEOPLE = 'GET_PEOPLE';
export const GET_PEOPLE_START = 'GET_PEOPLE_START';
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const GET_PEOPLE_FAIL = 'GET_PEOPLE_FAIL';
